### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by LYoung520** [samemon/Voice-to-Age#3]
I met an error when I tried to run the program. Can you give any advice on how to solve it?

This is the error message.

**_LYoungdeMacBook-Pro:~ lyoung$ python /Users/lyoung/Repository/Voice-to-Age-master/voice2age.py /Users/lyoung/Desktop/1243501.v.wav 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/lyoung/Repository/Voice-to-Age-master/voice2age.py", line 51, in <module>
    model = load_model("age_range_classifier.h5")
  File "/usr/local/lib/python2.7/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/usr/local/lib/python2.7/site-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/Users/lyoung/Library/Python/2.7/lib/python/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/Users/lyoung/Library/Python/2.7/lib/python/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'age_range_classifier.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)_**

Thanks a lot!

**Comment by eseku** [comment]
Hey man did you ever get round to fixing this?

**Comment by shara9712** [comment]
Hi! I have been having the same issue. Please do let me know if anyone has found a fix.
